// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/limit_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/limit_service.go -destination=internal/service/mock/limit_service_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	dto "github.com/hadi-projects/xyz-finance-go/internal/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockLimitService is a mock of LimitService interface.
type MockLimitService struct {
	ctrl     *gomock.Controller
	recorder *MockLimitServiceMockRecorder
	isgomock struct{}
}

// MockLimitServiceMockRecorder is the mock recorder for MockLimitService.
type MockLimitServiceMockRecorder struct {
	mock *MockLimitService
}

// NewMockLimitService creates a new mock instance.
func NewMockLimitService(ctrl *gomock.Controller) *MockLimitService {
	mock := &MockLimitService{ctrl: ctrl}
	mock.recorder = &MockLimitServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimitService) EXPECT() *MockLimitServiceMockRecorder {
	return m.recorder
}

// CreateLimit mocks base method.
func (m *MockLimitService) CreateLimit(req dto.CreateLimitRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLimit", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateLimit indicates an expected call of CreateLimit.
func (mr *MockLimitServiceMockRecorder) CreateLimit(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLimit", reflect.TypeOf((*MockLimitService)(nil).CreateLimit), req)
}

// DeleteLimit mocks base method.
func (m *MockLimitService) DeleteLimit(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteLimit", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteLimit indicates an expected call of DeleteLimit.
func (mr *MockLimitServiceMockRecorder) DeleteLimit(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteLimit", reflect.TypeOf((*MockLimitService)(nil).DeleteLimit), id)
}

// GetLimits mocks base method.
func (m *MockLimitService) GetLimits(userId uint) ([]dto.LimitResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLimits", userId)
	ret0, _ := ret[0].([]dto.LimitResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLimits indicates an expected call of GetLimits.
func (mr *MockLimitServiceMockRecorder) GetLimits(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLimits", reflect.TypeOf((*MockLimitService)(nil).GetLimits), userId)
}

// UpdateLimit mocks base method.
func (m *MockLimitService) UpdateLimit(id uint, req dto.UpdateLimitRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLimit", id, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLimit indicates an expected call of UpdateLimit.
func (mr *MockLimitServiceMockRecorder) UpdateLimit(id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLimit", reflect.TypeOf((*MockLimitService)(nil).UpdateLimit), id, req)
}
