// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/limit_mutation_repository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	entity "github.com/hadi-projects/xyz-finance-go/internal/entity"
	repository "github.com/hadi-projects/xyz-finance-go/internal/repository"
	gomock "go.uber.org/mock/gomock"
	gorm "gorm.io/gorm"
)

// MockLimitMutationRepository is a mock of LimitMutationRepository interface.
type MockLimitMutationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLimitMutationRepositoryMockRecorder
}

// MockLimitMutationRepositoryMockRecorder is the mock recorder for MockLimitMutationRepository.
type MockLimitMutationRepositoryMockRecorder struct {
	mock *MockLimitMutationRepository
}

// NewMockLimitMutationRepository creates a new mock instance.
func NewMockLimitMutationRepository(ctrl *gomock.Controller) *MockLimitMutationRepository {
	mock := &MockLimitMutationRepository{ctrl: ctrl}
	mock.recorder = &MockLimitMutationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimitMutationRepository) EXPECT() *MockLimitMutationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLimitMutationRepository) Create(mutation *entity.LimitMutation) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", mutation)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLimitMutationRepositoryMockRecorder) Create(mutation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLimitMutationRepository)(nil).Create), mutation)
}

// WithTx mocks base method.
func (m *MockLimitMutationRepository) WithTx(tx *gorm.DB) repository.LimitMutationRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.LimitMutationRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockLimitMutationRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockLimitMutationRepository)(nil).WithTx), tx)
}
