// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/limit_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/limit_repository.go -destination=internal/repository/mock/limit_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	"reflect"

	entity "github.com/hadi-projects/xyz-finance-go/internal/entity"
	"github.com/hadi-projects/xyz-finance-go/internal/repository"
	gomock "go.uber.org/mock/gomock"
	"gorm.io/gorm"
)

// MockLimitRepository is a mock of LimitRepository interface.
type MockLimitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLimitRepositoryMockRecorder
	isgomock struct{}
}

// MockLimitRepositoryMockRecorder is the mock recorder for MockLimitRepository.
type MockLimitRepositoryMockRecorder struct {
	mock *MockLimitRepository
}

// NewMockLimitRepository creates a new mock instance.
func NewMockLimitRepository(ctrl *gomock.Controller) *MockLimitRepository {
	mock := &MockLimitRepository{ctrl: ctrl}
	mock.recorder = &MockLimitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLimitRepository) EXPECT() *MockLimitRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockLimitRepository) Create(user *entity.TenorLimit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockLimitRepositoryMockRecorder) Create(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockLimitRepository)(nil).Create), user)
}

// Delete mocks base method.
func (m *MockLimitRepository) Delete(id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockLimitRepositoryMockRecorder) Delete(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockLimitRepository)(nil).Delete), id)
}

// FindByEmail mocks base method.
func (m *MockLimitRepository) FindByEmail(email string) (*entity.TenorLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByEmail", email)
	ret0, _ := ret[0].(*entity.TenorLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByEmail indicates an expected call of FindByEmail.
func (mr *MockLimitRepositoryMockRecorder) FindByEmail(email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByEmail", reflect.TypeOf((*MockLimitRepository)(nil).FindByEmail), email)
}

// FindByID mocks base method.
func (m *MockLimitRepository) FindByID(id uint) (*entity.TenorLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", id)
	ret0, _ := ret[0].(*entity.TenorLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockLimitRepositoryMockRecorder) FindByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockLimitRepository)(nil).FindByID), id)
}

// FindByUserID mocks base method.
func (m *MockLimitRepository) FindByUserID(userId uint) ([]entity.TenorLimit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", userId)
	ret0, _ := ret[0].([]entity.TenorLimit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockLimitRepositoryMockRecorder) FindByUserID(userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockLimitRepository)(nil).FindByUserID), userId)
}

// Update mocks base method.
func (m *MockLimitRepository) Update(user *entity.TenorLimit) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockLimitRepositoryMockRecorder) Update(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockLimitRepository)(nil).Update), user)
}

// GetUserIDByLimitID mocks base method.
func (m *MockLimitRepository) GetUserIDByLimitID(limitID uint) (uint, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserIDByLimitID", limitID)
	ret0, _ := ret[0].(uint)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserIDByLimitID indicates an expected call of GetUserIDByLimitID.
func (mr *MockLimitRepositoryMockRecorder) GetUserIDByLimitID(limitID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserIDByLimitID", reflect.TypeOf((*MockLimitRepository)(nil).GetUserIDByLimitID), limitID)
}

// WithTx mocks base method.
func (m *MockLimitRepository) WithTx(tx *gorm.DB) repository.LimitRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.LimitRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockLimitRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockLimitRepository)(nil).WithTx), tx)
}
